"""
Application configuration using Pydantic Settings.

All configuration is loaded from environment variables (or a .env file).
Missing required keys raise a descriptive error at startup rather than
failing silently mid-pipeline.
"""

from __future__ import annotations

import sys
from functools import lru_cache
from pathlib import Path
from typing import Optional

from pydantic import Field, field_validator, model_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


class AppConfig(BaseSettings):
    """
    Typed, validated application configuration.

    Values are read from environment variables or a .env file located in the
    project root. See .env.example for the full list of supported variables.
    """

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=False,
        extra="ignore",
    )

    # ------------------------------------------------------------------ #
    # LLM Configuration
    # ------------------------------------------------------------------ #

    anthropic_api_key: str = Field(
        description="Anthropic API key for Claude models",
    )
    openai_api_key: Optional[str] = Field(
        default=None,
        description="OpenAI API key used as fallback LLM",
    )
    anthropic_model: str = Field(
        default="claude-sonnet-4-5",
        description="Anthropic model ID to use as primary LLM",
    )
    openai_model: str = Field(
        default="gpt-4o",
        description="OpenAI model ID to use as fallback LLM",
    )
    llm_temperature: float = Field(
        default=0.2,
        ge=0.0,
        le=1.0,
        description="Sampling temperature for LLM responses",
    )
    llm_max_tokens: int = Field(
        default=4096,
        ge=256,
        le=16384,
        description="Maximum tokens for a single LLM response",
    )

    # ------------------------------------------------------------------ #
    # Search API Configuration
    # ------------------------------------------------------------------ #

    brave_search_api_key: Optional[str] = Field(
        default=None,
        description="Brave Search API key for web search",
    )

    # ------------------------------------------------------------------ #
    # Research Pipeline Configuration
    # ------------------------------------------------------------------ #

    max_search_results: int = Field(
        default=10,
        ge=1,
        le=50,
        description="Max results per source per sub-question",
    )
    max_revision_loops: int = Field(
        default=2,
        ge=0,
        le=5,
        description="Max Writer→Critic revision cycles",
    )
    quality_threshold: float = Field(
        default=0.75,
        ge=0.0,
        le=1.0,
        description="Quality score below which revision is triggered",
    )
    max_sub_questions: int = Field(
        default=5,
        ge=2,
        le=8,
        description="Max sub-questions generated by the Planner",
    )

    # ------------------------------------------------------------------ #
    # Logging
    # ------------------------------------------------------------------ #

    log_level: str = Field(
        default="INFO",
        description="Logging level: DEBUG, INFO, WARNING, ERROR",
    )

    # ------------------------------------------------------------------ #
    # Derived Properties
    # ------------------------------------------------------------------ #

    @property
    def project_root(self) -> Path:
        """Absolute path to the project root directory."""
        return Path(__file__).parent.parent

    @property
    def mcp_servers_dir(self) -> Path:
        """Directory containing MCP server scripts."""
        return self.project_root / "src" / "mcp_servers"

    @property
    def has_brave_search(self) -> bool:
        """Whether Brave Search is available."""
        return bool(self.brave_search_api_key)

    @property
    def has_openai_fallback(self) -> bool:
        """Whether OpenAI fallback is available."""
        return bool(self.openai_api_key)

    # ------------------------------------------------------------------ #
    # Validators
    # ------------------------------------------------------------------ #

    @field_validator("anthropic_api_key")
    @classmethod
    def validate_anthropic_key(cls, v: str) -> str:
        if not v or v == "your_anthropic_api_key_here":
            print(
                "\n[ERROR] ANTHROPIC_API_KEY is not set.\n"
                "  1. Copy .env.example to .env\n"
                "  2. Add your Anthropic API key from https://console.anthropic.com/\n",
                file=sys.stderr,
            )
            raise ValueError("ANTHROPIC_API_KEY must be set to a valid key")
        return v

    @field_validator("log_level")
    @classmethod
    def validate_log_level(cls, v: str) -> str:
        valid = {"DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"}
        upper = v.upper()
        if upper not in valid:
            raise ValueError(f"log_level must be one of {valid}, got '{v}'")
        return upper

    @model_validator(mode="after")
    def warn_missing_optional_keys(self) -> AppConfig:
        """Emit warnings for missing optional but recommended keys."""
        warnings = []
        if not self.brave_search_api_key:
            warnings.append(
                "BRAVE_SEARCH_API_KEY not set — web search will be unavailable. "
                "ArXiv and Wikipedia searches will still work."
            )
        if not self.openai_api_key:
            warnings.append(
                "OPENAI_API_KEY not set — no fallback LLM available if Anthropic fails."
            )
        for warning in warnings:
            print(f"[WARNING] {warning}", file=sys.stderr)
        return self


@lru_cache(maxsize=1)
def get_config() -> AppConfig:
    """
    Return the singleton application config.

    Uses lru_cache so the .env file is only read once per process.
    """
    return AppConfig()
